# Add this new section at the top
frontend:
  url: http://localhost:3000

# Add this property under the server block
server:
  forward-headers-strategy: native
  port: 8080
  servlet:
    session:
      cookie:
        # This will be overridden by environment variables in production
        same-site: lax

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/joblistingapp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS